AWSTemplateFormatVersion: 2010-09-09

Resources:
  HostRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-EC2-Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action: sts:AssumeRole

  HostInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref HostRole
      InstanceProfileName: !Sub ${AWS::StackName}-HostInstanceProfile

  ASGLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${AWS::StackName}-LaunchTemplate
      LaunchTemplateData:
        IamInstanceProfile:
          Arn: !GetAtt HostInstanceProfile.Arn
        ImageId: ami-0be2609ba883822ec
        InstanceType: t2.micro

  ASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: 0
      MaxSize: 5
      DesiredCapacity: 0
      LaunchTemplate:
        LaunchTemplateId: !Ref ASGLaunchTemplate
        Version: !GetAtt ASGLaunchTemplate.LatestVersionNumber
      AvailabilityZones:
        - !Select
          - 0
          - Fn::GetAZs: !Ref AWS::Region
      LifecycleHookSpecificationList:
        - LifecycleTransition: autoscaling:EC2_INSTANCE_LAUNCHING
          DefaultResult: ABANDON
          HeartbeatTimeout: 120
          LifecycleHookName: !Sub ${AWS::StackName}-LifecycleHookLaunching

Outputs:
  ASGName:
    Description: ASG Name
    Value: !Ref ASG
  ASGLifecycleHookLaunchingName:
    Description: ASG Livecycle Hook Launching Name
    Value: !Sub ${AWS::StackName}-LifecycleHookLaunching
